# CORS 활성화
http.cors.enabled: true

# CORS 요청을 허용할 오리진 (Vue 앱이 실행되는 도메인)
http.cors.allow-origin: "http://localhost:5173"  # 프론트엔드 도메인

# 허용할 HTTP 메서드 설정
http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"

# 허용할 HTTP 헤더 설정
http.cors.allow-headers: "X-Requested-With, Content-Type, Authorization"

# 자격 증명 포함 여부 (필요 시)
http.cors.allow-credentials: false
