springdoc:
  swagger-ui:
    path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-service.default.svc.cluster.local:3306/debook_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  elasticsearch:
    rest:
      uris: http://elasticsearch.default.svc.cluster.local:9200
      username: "elastic"
      password: "elastic"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  redis:
    data:
      host: ${REDIS_DATA_HOST}
      port: ${REDIS_DATA_PORT}
  devtools:
    restart:
      enabled: false

  data:
    mongodb:
      uri: mongodb://mongodb-service.default.svc.cluster.local:27017/debook

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

kakao:
  client_id:
    rest_api_key: ${KAKAO_CLIENT_ID_REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI}

token:
  secret: ${TOKEN_SECRET}
  access_token_expiration_time: ${TOKEN_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh_token_expiration_time: ${TOKEN_REFRESH_TOKEN_EXPIRATION_TIME}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ap-southeast-2
    credentials:
      accessKey: ${IM_ACCESS}
      secretKey: ${IM_SECRET}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
